AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  url-shortener-backend
  A URL shortener with Firebase Auth, DynamoDB and API Gateway.

Globals:
  Function:
    Timeout: 10
    Environment:
      Variables:
        SHORT_URLS_TABLE: !Ref ShortURLsTable
        CLICK_EVENTS_TABLE: !Ref ClickEventsTable
        FIREBASE_SSM_PATH: "/cortaurl-firebase"

Parameters:
  FirebaseProjectId:
    Type: String
    Description: Firebase Project ID
  FirebasePrivateKeyId:
    Type: String
    Description: Firebase Private Key ID
  FirebasePrivateKey:
    Type: String
    Description: Firebase Private Key
    NoEcho: true
  FirebaseClientEmail:
    Type: String
    Description: Firebase Client Email
  FirebaseClientId:
    Type: String
    Description: Firebase Client ID
  FirebaseClientCertUrl:
    Type: String
    Description: Firebase Client Certificate URL

Resources:
  ShortURLsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: ShortURLs
      AttributeDefinitions:
        - AttributeName: short_code
          AttributeType: S
      KeySchema:
        - AttributeName: short_code
          KeyType: HASH
      BillingMode: PAY_PER_REQUEST

  ClickEventsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: ClickEvents
      AttributeDefinitions:
        - AttributeName: short_code
          AttributeType: S
        - AttributeName: timestamp
          AttributeType: S
      KeySchema:
        - AttributeName: short_code
          KeyType: HASH
        - AttributeName: timestamp
          KeyType: RANGE
      BillingMode: PAY_PER_REQUEST

  SharedLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      LayerName: shared-layer
      Description: "Shared code for all functions"
      ContentUri: layers/shared/
      CompatibleRuntimes:
        - python3.13

  # --- Lambda Functions ---
  ShortenFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: ShortenFunction
      CodeUri: functions/shorten/
      Handler: app.lambda_handler
      Runtime: python3.13
      Architectures: [x86_64]
      Layers: [!Ref SharedLayer]
      Events:
        ShortenApi:
          Type: Api
          Properties:
            Path: /shorten
            Method: POST
            RestApiId: !Ref ApiGateway
        ShortenApiOptions:
          Type: Api
          Properties:
            Path: /shorten
            Method: OPTIONS
            RestApiId: !Ref ApiGateway
      Policies:
        - DynamoDBCrudPolicy: {TableName: !Ref ShortURLsTable}
        - Version: "2012-10-17"
          Statement:
            - Effect: Allow 
              Action:
                - "ssm:GetParameter"
              Resource: !Sub "arn:aws:ssm:${AWS::Region}:${AWS::AccountId}:parameter/cortaurl-firebase"

  DeleteUrlFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: DeleteUrlFunction
      CodeUri: functions/delete_url/
      Handler: app.lambda_handler
      Runtime: python3.13
      Architectures: [x86_64]
      Layers: [!Ref SharedLayer]
      Events:
        DeleteUrlApi:
          Type: Api
          Properties:
            Path: /urls/{short_code}
            Method: DELETE
            RestApiId: !Ref ApiGateway
        DeleteUrlApiOptions:
          Type: Api
          Properties:
            Path: /urls/{short_code}
            Method: OPTIONS
            RestApiId: !Ref ApiGateway
      Policies:
        - DynamoDBCrudPolicy: {TableName: !Ref ShortURLsTable}
        - Version: "2012-10-17"
          Statement:
            - Effect: Allow 
              Action:
                - "ssm:GetParameter"
              Resource: !Sub "arn:aws:ssm:${AWS::Region}:${AWS::AccountId}:parameter/cortaurl-firebase"

  RedirectFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: RedirectFunction
      CodeUri: functions/redirect/
      Handler: app.lambda_handler
      Runtime: python3.13
      Architectures: [x86_64]
      Layers: [!Ref SharedLayer]
      Environment: {Variables: {CLICK_EVENTS_TABLE: !Ref ClickEventsTable}}
      Events:
        RedirectApi:
          Type: Api
          Properties:
            Path: /{short_code}
            Method: GET
            RestApiId: !Ref ApiGateway
      Policies:
        - DynamoDBReadPolicy: {TableName: !Ref ShortURLsTable}
        - DynamoDBWritePolicy: {TableName: !Ref ClickEventsTable}
        - Version: "2012-10-17"
          Statement:
            - Effect: Allow 
              Action:
                - "ssm:GetParameter"
              Resource: !Sub "arn:aws:ssm:${AWS::Region}:${AWS::AccountId}:parameter/cortaurl-firebase"

  ListUrlsFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: ListUrlsFunction
      CodeUri: functions/list_urls/
      Handler: app.lambda_handler
      Runtime: python3.13
      Architectures: [x86_64]
      Layers: [!Ref SharedLayer]
      Events:
        ListUrlsApi:
          Type: Api
          Properties:
            Path: /urls
            Method: GET
            RestApiId: !Ref ApiGateway
        ListUrlsApiOptions:
          Type: Api
          Properties:
            Path: /urls
            Method: OPTIONS
            RestApiId: !Ref ApiGateway
      Policies:
        - DynamoDBReadPolicy: {TableName: !Ref ShortURLsTable}
        - Version: "2012-10-17"
          Statement:
            - Effect: Allow 
              Action:
                - "ssm:GetParameter"
              Resource: !Sub "arn:aws:ssm:${AWS::Region}:${AWS::AccountId}:parameter/cortaurl-firebase"

  AnalyticsFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: AnalyticsFunction
      CodeUri: functions/analytics/
      Handler: app.lambda_handler
      Runtime: python3.13
      Architectures: [x86_64]
      Layers: [!Ref SharedLayer]
      Environment: {Variables: {CLICK_EVENTS_TABLE: !Ref ClickEventsTable}}
      Events:
        AnalyticsApi:
          Type: Api
          Properties:
            Path: /urls/{short_code}/analytics
            Method: GET
            RestApiId: !Ref ApiGateway
      Policies:
        - DynamoDBReadPolicy: {TableName: !Ref ClickEventsTable}
        - DynamoDBReadPolicy: {TableName: !Ref ShortURLsTable}
        - Version: "2012-10-17"
          Statement:
            - Effect: Allow 
              Action:
                - "ssm:GetParameter"
              Resource: !Sub "arn:aws:ssm:${AWS::Region}:${AWS::AccountId}:parameter/cortaurl-firebase"

  ApiGateway:
    Type: AWS::Serverless::Api
    Properties:
      StageName: Prod
      Cors:
        AllowOrigin:
          - "https://cortaurl.com.br"
          - "https://www.cortaurl.com.br"
          - "http://localhost:5173"
        AllowHeaders:
          - Authorization
          - Content-Type
          - Accept
        AllowMethods:
          - GET
          - POST
          - DELETE
          - OPTIONS

Outputs:
  ApiUrl:
    Description: "API Gateway endpoint URL"
    Value: !Sub "https://${ApiGateway}.execute-api.${AWS::Region}.amazonaws.com/Prod/"