AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  url-shortener-backend

  Sample SAM Template for url-shortener-backend

Globals:
  Function:
    Timeout: 10
    Environment:
      Variables:
        SHORT_URLS_TABLE: !Ref ShortURLsTable

Resources:
  ShortURLsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: ShortURLs
      AttributeDefinitions:
        - AttributeName: short_code
          AttributeType: S
      KeySchema:
        - AttributeName: short_code
          KeyType: HASH
      BillingMode: PAY_PER_REQUEST

  SharedLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      LayerName: shared-layer
      Description: "Shared code for all functions"
      ContentUri: layers/shared/
      CompatibleRuntimes:
        - python3.13

  ShortenFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: ShortenFunction
      CodeUri: functions/shorten/
      Handler: app.lambda_handler
      Runtime: python3.13
      Architectures:
        - arm64
      Layers:
        - !Ref SharedLayer
      Environment:
        Variables:
          SHORT_URLS_TABLE: !Ref ShortURLsTable
      Events:
        ShortenApi:
          Type: Api
          Properties:
            Path: /shorten
            Method: POST
            RestApiId: !Ref ApiGateway

  ApiGateway:
    Type: AWS::Serverless::Api
    Properties:
      StageName: Prod
      Auth:
        DefaultAuthorizer: CognitoAuth
        Authorizers:
          CognitoAuth:
            UserPoolArn: !GetAtt UserPool.Arn

  UserPool:
    Type: AWS::Cognito::UserPool
    Properties:
      UserPoolName: ShortURLsUserPool

  UserPoolClient:
    Type: AWS::Cognito::UserPoolClient
    Properties:
      ClientName: ShortenerClient
      UserPoolId: !Ref UserPool
      GenerateSecret: false