AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  url-shortener-backend

  Sample SAM Template for url-shortener-backend

Resources:
  ShortURLsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: ShortURLs
      AttributeDefinitions:
        - AttributeName: short_code
          AttributeType: S
      KeySchema:
        - AttributeName: short_code
          KeyType: HASH
      BillingMode: PAY_PER_REQUEST
  
  UserPool:
    Type: AWS::Cognito::UserPool
    Properties:
      UserPoolName: ShortURLsUserPool
    
  UserPoolClient:
    Type: AWS::Cognito::UserPoolClient
    Properties:
      ClientName: ShortenerClient
      UserPoolId: !Ref UserPool
      GenerateSecret: false